# Generated by Django 5.1.4 on 2024-12-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
