# Generated by Django 5.1.4 on 2024-12-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_carousel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='first_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='second_text',
            field=models.CharField(max_length=100),
        ),
    ]
