# Generated by Django 5.1.4 on 2024-12-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_alter_meeting_first_text_alter_meeting_second_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='division',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='invitation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
