# Generated by Django 5.1.4 on 2024-12-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_meeting_division_alter_meeting_invitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middle',
            name='last',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='middle',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='middle',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
