# Generated by Django 5.1.4 on 2024-12-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_middle_last_alter_middle_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
