# Generated by Django 5.1.4 on 2024-12-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_alter_about_text_alter_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popular',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='popular',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
