# Generated by Django 5.1.4 on 2024-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_popular_text_alter_popular_price_alter_popular_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
