# Generated by Django 5.1.4 on 2024-12-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_alter_end_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='end',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
